#source "https://rubygems.org"

#ruby "2.6.0"

#gem "sinatra"
#gem "sinatra-contrib"
#gem "erubis"
#gem "rack-test"
#gem "minitest"
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "erubis"

gem "minitest"
gem "rack-test"